// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smcqjescwimmdyoiwliu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtY3FqZXNjd2ltbWR5b2l3bGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MDYwMzksImV4cCI6MjA2MzM4MjAzOX0.TLjsvHI0tngle92CjftSL1xF4KB6SjOOc1vrCTXVHqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});